name: stracker
description: "An Islamic worship companion app to track Salawat and spiritual habits."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase core
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_analytics: ^10.8.4


  # ✅ Local Storage & Notifications
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2

  # ✅ State Management & UI
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # ✅ Graphs and Progress UI
  fl_chart: ^0.64.0
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
